FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -pl NotificationService -am -DskipTests

FROM eclipse-temurin:21-jre
COPY --from=build /app/NotificationService/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]