export const GET_AI_ANALYSIS_REQUEST = "GET_AI_ANALYSIS_REQUEST";
export const GET_AI_ANALYSIS_SUCCESS = "GET_AI_ANALYSIS_SUCCESS";
export const GET_AI_ANALYSIS_FAILURE = "GET_AI_ANALYSIS_FAILURE";

export const TRIGGER_AI_ANALYSIS_REQUEST = "TRIGGER_AI_ANALYSIS_REQUEST";
export const TRIGGER_AI_ANALYSIS_SUCCESS = "TRIGGER_AI_ANALYSIS_SUCCESS";
export const TRIGGER_AI_ANALYSIS_FAILURE = "TRIGGER_AI_ANALYSIS_FAILURE";

export const UPDATE_PROFILE_PIC_SUCCESS = "UPDATE_PROFILE_PIC_SUCCESS";
export const UPDATE_PROFILE_PIC_FAILURE = "UPDATE_PROFILE_PIC_FAILURE";
export const UPDATE_PROFILE_PIC_REQUEST = "UPDATE_PROFILE_PIC_REQUEST";

export const VERIFY_EMAIL_SUCCESS = "VERIFY_EMAIL_SUCCESS";
export const VERIFY_EMAIL_REQUEST = "VERIFY_EMAIL_REQUEST";
export const VERIFY_EMAIL_FAILURE = "VERIFY_EMAIL_FAILURE";

export const RESEND_FAILURE = "RESEND_FAILURE";
export const RESEND_SUCCESS = "RESEND_SUCCESS";
export const RESEND_REQUEST = "RESEND_REQUEST";

export const USER_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USER_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USER_PROFILE_FAILURE = "USER_PROFILE_FAILURE";

export const UPLOAD_PROFILE_PICTURE_REQUEST = "UPLOAD_PROFILE_PICTURE_REQUEST";
export const UPLOAD_PROFILE_PICTURE_SUCCESS = "UPLOAD_PROFILE_PICTURE_SUCCESS";
export const UPLOAD_PROFILE_PICTURE_FAILURE = "UPLOAD_PROFILE_PICTURE_FAILURE";

export const UPDATE_PROFILE_REQUEST = "UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";

export const REFRESH_TOKENS_REQUEST = "REFRESH_TOKENS_REQUEST";
export const REFRESH_TOKENS_SUCCESS = "REFRESH_TOKENS_SUCCESS";
export const REFRESH_TOKENS_FAILURE = "REFRESH_TOKENS_FAILURE";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILURE = "RESET_PASSWORD_FAILURE";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const GET_PROFILE_REQUEST = "GET_PROFILE_REQUEST";
export const GET_PROFILE_FAILURE = "GET_PROFILE_FAILURE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";

export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";
export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";

export const SHOW_SESSION_ALERT = "SHOW_SESSION_ALERT";
export const HIDE_SESSION_ALERT = "HIDE_SESSION_ALERT";

export const LOGOUT = "LOGOUT";