
#Database Config
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.config.ignoreUnresolvablePlaceholders=true

#JWT Config
jwt.secret=${JWT_SECRET}

#Secret Key S3 bucket
application.bucket.name=${APPLICATION_BUCKET_NAME}
aws.access-key=${AWS_ACCESS_KEY}
aws.secret-key=${AWS_SECRET_KEY}
aws.region=${AWS_REGION}

# Gmail SMTP settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}   # Your Gmail address
spring.mail.password=${MAIL_PASSWORD}   # Your Gmail App Password (see note below)
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=30000
spring.mail.properties.mail.smtp.timeout=30000
spring.mail.properties.mail.smtp.writetimeout=30000
notification.service.template.folder=notification-templates

# Application base URL
appBaseUrl.url=${APP_BASE_URL}

notification.service.endpoint.url=${NOTIFICATION_SERVICE_URL}
notification.system.email.address=${NOTIFICATION_SYSTEM_EMAIL_ADDRESS}
logging.level.oneconnect.za.smp.subscription.controllers=DEBUG
logging.level.oneconnect.za.smp.subscription.services=DEBUG

#CLOUD FRONT
cloudfront.domain=${CLOUDFRONT_DOMAIN}
cloudfront.private-key=${CLOUDFRONT_PRIVATE_KEY}
cloudfront.key-pair-id=${CLOUDFRONT_KEY_PAIR_ID}

server.tomcat.max-swallow-size=1GB
server.tomcat.max-http-form-post-size=1GB